apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-bucket-config
  namespace: monitoring
data:
  bucket-config.yml: |
    type: S3
    config:
      bucket: thanos-metrics-bucket405
      endpoint: s3.ap-southeast-2.amazonaws.com
      access_key: ${AWS_ACCESS_KEY_ID}
      secret_key: ${AWS_SECRET_ACCESS_KEY}

