apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-metrics-full-access
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: ["policy"]
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: ["autoscaling"]
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: ["certificates.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: ["extensions"]
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list"]

