apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-state-metrics-full-access-binding
subjects:
  - kind: ServiceAccount
    name: kube-state-metrics-sa
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: kube-state-metrics-full-access
  apiGroup: rbac.authorization.k8s.io

